[impress]
project_name="Unknown project name"
author="Unknown author"
status="Unknown status"
additional_info=""
project_link=""

[camera]
url="balser-api:5050"
exposure_time_microseconds=10000
# camera address
serial_number=""
ip_address=""
timeout=""
transmission_type=""
destination_ip_address=""
destination_port=""
# debugging
emulate_camera=false

[model]
filename="model.onnx"
folder_head="/home/app/"
folder_data="data/"
class_map=""
color_map=""
image_size=[640, 640]
precision="fp32"