[impress]
project_name="Unknown project name"
author="Unknown author"
status="Unknown status"
additional_info=""
project_link=""

[camera]
url="http://localhost:5051/test/image"
exposure_time_microseconds=10000
# camera address
serial_number=""
ip_address=""
timeout=""
transmission_type=""
destination_ip_address=""
destination_port=""
image_extension=".bmp"
# debugging
emulate_camera=false

[model]
url="http://localhost:5052/inference"
folder_head="/home/app/"
folder_data="data/"
class_map=""
color_map=""

[general]
file_type_save_image=".webp"
#file_box_pattern="../data/desired_coordinates.yml"
#image_size=[640,544]
#image_size=[640,544]