prefix="FE"


[impress]
project_name="Unknown project name"
author="Unknown author"
status="Unknown status"
#additional_info=""
project_link=""


[camera]
exposure_time_microseconds=10000
# camera address
serial_number=""
ip_address=""
subnet_mask=""
timeout=""
transmission_type=""
destination_ip_address=""
destination_port=""
image_extension=".jpg"
# debugging
emulate_camera=false
# image
image_format="jpeg"
image_quality=85


[general]
url_backend="http://backend:5050/main"
#url_backend="http://localhost:5050/main"  # FIXME: for debugging
file_type_save_image=".jpg"
data_folder="./data"
timeout=10000

