prefix="FE"


[impress]
project_name="Unknown project name"
author="Unknown author"
status="Unknown status"
#additional_info=""
project_link=""


[camera]
exposure_time_microseconds=10000
# camera address
serial_number=""
ip_address=""
subnet_mask=""
timeout=""  # seconds
transmission_type=""
destination_ip_address=""
destination_port=""
image_extension=".jpg"
# image
pixel_type="BayerRG8"
convert_to_format="RGB"
# image
[camera.image]
format="jpeg"
quality=100


[backend]
url_backend="http://backend:5051/main/with-camera"
#url_backend="http://localhost:5051/main/with-camera"  # FIXME: for debugging
auth_token="4vrGhC7W"
timeout=10000

[general]
file_type_save_image=".jpg"
data_folder="./data"
#title=
#description=
#image_size