version: '3'

services:
   # ----- toy inference
  basler-camera-service:
    container_name: basler-api
    build:
      context: ./
      dockerfile: BaslerAPI.Dockerfile
    image: schwmax/basler-api
#    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      # customize
      - TEST_IMAGE=/home/app/testimage.bmp
    volumes:
      - ./BaslerAPI/230221_143518_0000001264_CAM1_NORMAL_OK.bmp:/home/app/testimage.bmp
    ports:
      - 3956:3956
      - 46000:46000/udp  # set Streaming Port to fixed value with pylonViewer
      - 5005:5050  # external access port | only for debugging

  inference-backend:
    container_name: backend-onnx
    build:
      context: ./
      dockerfile: Backend.Dockerfile
    image: schwmax/toy-inference-backend
    environment:
      - TZ=Europe/Berlin
#      - MODEL_FILENAME=20240306_VIAB1-2_YOLOv7tiny.onnx
      - MODEL_IMAGE_SIZE=(544, 640)
      - MODEL_PRECISION=fp32
#      - MODEL_PRECISION=fp16
    volumes:
      - ./data/20240306_VIAB1-2_YOLOv7tiny.onnx:/home/app/data/model.onnx
#      - ./data/20240306_VIAB1-2_YOLOv7tiny.onnx_fp16:/home/app/data/model.onnx
    ports:
      - 5007:5050  # external access port | only for debugging

  inference-frontend:
    container_name: frontend-streamlit
    build:
      context: ./
      dockerfile: Frontend.Dockerfile
    image: schwmax/toy-inference-frontend

#    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      # variables to customize container
#      - PREFIX=TI
      - TI_GENERAL_TITLE="MVE for object recognition"
      - TI_GENERAL_DESCRIPTION="loreipsum ..."
      # model
      - TI_MODEL_URL=http://backend-onnx:5050/inference
#      - TI_MODEL_CLASS_MAP=
      - TI_MODEL_COLOR_MAP=colors.txt
#      - TI_MODEL_IMAGE_SIZE=(544, 640)
      # camera
      - TI_CAMERA_URL=http://basler-api:5050/test/image
#      - TI_CAMERA_URL=http://basler-api:5050/basler/take-photo
#      - TI_CAMERA_SERIAL_NUMBER=24339728
      - TI_CAMERA_IP_ADDRESS="192.168.10.5"
#      - TI_CAMERA_TIMEOUT
      - TI_CAMERA_TRANSMISSION_TYPE=Multicast
      - TI_CAMERA_DESTINATION_IP_ADDRESS="192.168.10.221"
      - TI_CAMERA_DESTINATION_PORT=46000
      - TI_CAMERA_EMULATE_CAMERA=True  # <<===== EMULATE CAMERA FOR DEMONSTRATION
      # impress
      - TI_IMPRESS_PROJECT_NAME="Minimal Inference"
      - TI_IMPRESS_AUTHOR=SCHWMAX
#      - TI_IMPRESS_STATUS
#      - TI_IMPRESS_ADDITIONAL_INFO
      - TI_IMPRESS_PROJECT_LINK=https://github.com/max-scw/MinimalInferenceUI.git
    volumes:
      # mount model into container
#      - ./UIdata/20240306_VIAB1-2_YOLOv7tiny.onnx:/home/app/model.onnx
      - ./data/:/home/app/data/:rw
    ports:
      - 5006:8501  # external access port

