services:
  basler-camera-service:
    container_name: camera-adapter
    image: maxscw/baslercameraadapter:v0.2.20
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LOGGING_LEVEL=DEBUG
      - FRAMES_PER_SECOND=10
      - PIXEL_TYPE=Mono8
    volumes:
      - ./testimages:/home/app/test
    ports:
      - 3956:3956
      - 46000:46000/udp  # set Streaming Port to fixed value with pylonViewer
      - 5005:5050  # external access port | for debugging

  inference-service:
    container_name: inference
    build:
      context: ./
      dockerfile: Inference.Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LOGGING_LEVEL=DEBUG
#      - MODEL_FILENAME=yolov7-tiny.onnx
      - MODEL_IMAGE_SIZE=(544, 640)
      - MODEL_PRECISION=fp32
#      - MODEL_PRECISION=fp16
    volumes:
      - ./models/yolov7-tiny.onnx:/home/app/data/model.onnx:ro
#      - ./models/yolov7-tiny.onnx_fp16:/home/app/data/model.onnx
    ports:
      - 5006:5050  # external access port | only for debugging

  backend-service:
    container_name: backend
    build:
      context: ./
      dockerfile: Backend.Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LOGGING_LEVEL=DEBUG
      - BE_INFERENCE_URL=http://inference:5050/inference
      - BE_CAMERA_URL=http://camera-adapter:5050/basler/continuous-acquisition/get-image
#      - BE_CAMERA_SERIAL_NUMBER0
      - BE_CAMERA_IP_ADDRESS=
      - BE_CAMERA_TRANSMISSION_TYPE=Multicast
      - BE_CAMERA_DESTINATION_IP_ADDRESS=
      - BE_CAMERA_DESTINATION_PORT=4600
#      - BE_CAMERA_IMAGE_FORMAT=jpg
#      - BE_CAMERA_IMAGE_QUALITY=75
      - BE_CAMERA_EMULATE_CAMERA=true
      # general
      - BE_GENERAL_SAVE_IMAGES=all
    volumes:
      - ./data:/home/app/data/:rw
    ports:
      - 5000:5050  # external access port | only for debugging

  inference-frontend:
    container_name: frontend-streamlit
    build:
      context: ./
      dockerfile: Frontend.Dockerfile
    image: schwmax/toy-inference-frontend
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      # variables to customize container
#      - PREFIX=FE
      # general configs
      - FE_GENERAL_URL_BACKEND="http://backend:5050/main"
#      -
#      - TI_GENERAL_TITLE="MVE for object recognition"
#      - TI_GENERAL_DESCRIPTION="loreipsum ..."
      # camera
#      - FE_CAMERA_SERIAL_NUMBER=0
      - FE_CAMERA_IP_ADDRESS=192.168.10.5
      - FE_CAMERA_SUBNET_MASK=255.255.255.0
      - FE_CAMERA_TRANSMISSION_TYPE=Multicast
      - FE_CAMERA_DESTINATION_IP_ADDRESS=192.168.10.223
      - FE_CAMERA_DESTINATION_PORT=46000
#      - FE_CAMERA_EMULATE_CAMERA=True  # <<===== EMULATE CAMERA FOR DEMONSTRATION
      - FE_CAMERA_IMAGE_EXTENSION=.jpg
      - FE_CAMERA_IMAGE_FORMAT=jpeg
      - FE_CAMERA_IMAGE_QUALITY=75
      # impress
      - FE_IMPRESS_PROJECT_NAME="Minimal Inference"
      - FE_IMPRESS_AUTHOR=SCHWMAX
#      - TI_IMPRESS_STATUS
#      - TI_IMPRESS_ADDITIONAL_INFO
      - FE_IMPRESS_PROJECT_LINK=https://github.com/max-scw/MinimalImageInferenceService.git

      # streamlit
      - STREAMLIT_THEME_PRIMARY_COLOR=#2D4275
    volumes:
      # mount folder to save images to
      - ./data/:/home/app/data/:rw
    ports:
      - 5001:8501  # external access port

