prefix="BE"

[inference]
url="http://inference:5050/inference"
#url="http://localhost:5052/inference"


[camera]
url="http://camera-adapter:5050/basler/take-photo"
#url="http://localhost:5051/basler/take-photo"

serial_number=0
ip_address="1.1.1.1"
emulate_camera=true
#serial_number=
#ip_address=
#timeout=
#transmission_type=
#destination_ip_address=
#destination_port=
#format="jpg"
#quality=75
image_extension=".jpg"

[model]
folder_head="./"
folder_data="data"
mappings=""

[general]
save_images="all"  # literal: "all", "every x", "no"
save_images_with_failed_pattern_check=true
folder_saved_images="data"
