prefix="BE"

[inference]
url="http://inference:5050/inference"
#url="http://localhost:5052/inference"


[camera]
url="http://camera-adapter:5050/basler/single-frame-acquisition/take-photo"
#url="http://localhost:5051/basler/single-frame-acquisition/take-photo"

serial_number=0
ip_address="1.1.1.1"
emulate_camera=true
#transmission_type=
#destination_ip_address=
#destination_port=
#timeout=
image_extension=".jpg"
#pixel_format="Mono"

[image]
#format="jpg"
#quality=75

[model]
folder_head="./"
folder_data="data"
mapping=""

[general]
save_images="all"  # literal: "all", "every x", "no"
save_images_with_failed_pattern_check=true
folder_saved_images="data"
