prefix="BE"

[inference]
#url="http://inference:5050/inference"
#url="http://localhost:5052/inference"
timeout=2  # seconds
#auth_token="UTvK7oF9"



[camera]
url="http://camera-adapter:5050/basler/take-photo"
#url="http://localhost:5051/basler/take-photo"
#auth_token="4vrGhC7W"

serial_number=""
ip_address=""
#transmission_type=
#destination_ip_address=
#destination_port=
timeout=4  # seconds
image_extension=".jpg"
#pixel_format="Mono"

[camera.image]
#format="jpg"
#quality=75
#rotation_angle=180

[model]
folder_head="./"
folder_data="data"
mapping=""

[general]
save_images="all"  # literal: "all", "every x", "no"
save_images_with_failed_pattern_check=true
folder_saved_images="data"
image_quality=100

[pattern]
file="./data/"
#default=
