

[inference]
url="http://inference:5050/inference"
#url="http://localhost:5052/inference"


[camera]
url="http://camera-adapter:5050/basler/take-photo"
#url="http://localhost:5051/basler/take-photo"

serial_number=1
ip_address="1.1.1.1"
emulate_camera=true
#serial_number=
#ip_address=
#timeout=
#transmission_type=
#destination_ip_address=
#destination_port=
#format="jpg"
#quality=75
image_extension=".jpg"

