global:
  scrape_interval: 10s

scrape_configs:
 - job_name: basler-camera
   static_configs:
    - targets:
       - camera-adapter:5050

 - job_name: backend
   static_configs:
    - targets:
       - backend-service:5050

 - job_name: inference
   static_configs:
    - targets:
       - inference-service:5050
