name: Build and Deploy Docker Containers

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, push and add metadata to containers
        run: |
          for dockerfile in $(ls Dockerfile*); do
            container_name=minimal-image-inference-service-${dockerfile#Dockerfile}
            echo "Building and pushing $container_name"
            docker build -t $container_name -f $dockerfile .
            docker tag $container_name ${{ secrets.DOCKER_USERNAME }}/$container_name
            if [ "$(git rev-parse HEAD)" != "$(git rev-parse HEAD~1)" ]; then
              docker push ${{ secrets.DOCKER_USERNAME }}/$container_name
              docker/metadata-action@v3 \
                images=${{ secrets.DOCKER_USERNAME }}/$container_name \
                tags=latest, $(date +'%Y-%m-%d'), $GITHUB_SHA, $version
            fi
          done

#curl -X POST \
#  https://api.github.com/repos/maxscw/MinimalImageInferenceService/actions/workflows/docker-build-deploy/trigger \
#  -H 'Content-Type: application/json' \
#  -d '{"ref":"main","inputs":{"version":"1.2.3"}}'
